#!/usr/bin/env bash

# Builds the app and creates the Docker images.

# Ensure env file is present - could make this more robust by checking each line inside template.env
# is included in .env to ensure all values have been included.
if [[ ! -f ".env" ]]; then
	echo "No .env file found. Please create one using template.env as a template."
	exit 1
fi

# Build the app
mvn package

# Separate the JAR into the layers we'll use in our Docker image.
rm -rf target/dependency
mkdir -p target/dependency
cd target/dependency
jar -xf ../*.jar
cd ../../

# Build the Docker image(s)
docker build -f dockerfiles/app.dockerfile -t dmoffat/dkpmanager .
docker build -f dockerfiles/nginx.dockerfile -t dmoffat/dkpmanager-nginx .