version: '3.1'
services:
  app:
    image: dmoffat/dkpmanager
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 9001:3306
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}