version: '3.1'
services:
  app:
    container_name: dkpmanager_app
    depends_on:
      - db
    image: dmoffat/dkpmanager
    ports:
      - 8080:8080
  db:
    container_name: dkpmanager_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    image: mysql
    restart: always
    ports:
      - 9001:3306