version: '3.1'
services:
  app:
    container_name: dkpmanager_app
    depends_on:
      - db
    image: dmoffat/dkpmanager
    ports:
      - 8080:8080
    volumes:
      - ./client/templates:/app/templates
      - ./target/classes/com:/app/com
      - ./target/classes/application.properties:/app/application.properties
      - ./target/classes/messages.properties:/app/messages.properties
  db:
    container_name: dkpmanager_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    image: mysql
    restart: always
    ports:
      - 9001:3306
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql