#!/usr/bin/env bash

# Development script, starts the backend

# Firstly, build the backend code, note: this could be extended to build the frontend code too, may
# need a flag for different environments.
./build-app

# Start the containers (database/app)
docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d

# Listen for changes to frontend assets - this will require an NPM install on the host machine!
npm run dev-server