package com.dmoffat.dkpmanager.dao;

import com.dmoffat.dkpmanager.model.Player;
import org.springframework.stereotype.Repository;

import javax.persistence.Query;
import java.util.List;

// todo: Fix SQL queries generated by this class
@Repository
public class PlayerDao extends HibernateDao<Player, Integer> {
    public Player findByEmail(String email) {
        Query query = entityManager().createQuery("from Player p where p.email = :email");
        query.setParameter("email", email);
        return getSingleResult(query);
    }

    public Player findByForgottenPasswordToken(String token) {
        Query query = entityManager().createQuery(
                "from Player p where p.forgottenPasswordToken = :forgottenPasswordToken");
        query.setParameter("forgottenPasswordToken", token);
        return getSingleResult(query);
    }

    public List<Player> findByGuildId(Integer guildId) {
        Query query = entityManager().createQuery(
                "from Player p where p.guild.id = :guildId");
        query.setParameter("guildId", guildId);
        return getResultList(query);
    }
}
